### ISSUE TITLE
Backpressure

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-pubsub#14]
Follow up for a comment by @mcollina on twitter:

> I have found that in (pseudo) real-time systems backpressure [of messages] is THE feature you need to act at scale.

Just to clarify... are we talking about `Stream` backpressure that is supposedly handled by `pipe()` or per message back pressure (eg. "hey stop sending me messages so frequently ...you are essentially DOSing me!").

This set of modules **only** supports the `Stream` and `net.Socket` style interfaces. It explicitely uses `pipe()` and only `pipe()`. Even the `Primus` compatability layer confroms to node's `Stream#pipe()` semantics (it implements a through stream that converts object mode data events to real `Buffer`s).

So if that is what @mcollina means by backpressure I think we can claim this as a feature. Although it sounds like there is a gotcha. Since there was some fix required to `mqtt.js` (which AFAIK only uses `Stream#pipe()`).

If we are talking about essentially throttling messages via the `Bridge` that is something different but very similar. We can get the same effect of not DOSing clients (eg. slow Java / battery sensitive Arduino) by throttling the sending of messages (instead of at the connection level). 

Essentially this...?

``` js
// when we are about to send a message
var delay = getDelay(connection.id, msg.id); // or something like this
setTimeout(trySend, delay);
```

@mcollina @piscisaureus @bajtos @bnoordhuis @sam-github any thoughts on this?

**Comment by mcollina** [comment]
The problem is this:
1. sender sends 1000 msg/sec
2. receiver can receive (via the TCP socket) 1000 msg/sec
3. receiver can process only 500 msg/sec
4. After a while the receiver crashes, as it saturates the event loop/process

The problem in mqtt-connection (and why it was ditched by MQTT.js) is that there is no way for processing 'one message at a time' at the application level, as they are only normal node events, i.e. no callback. So, I extracted all the parsing logic into [mqtt-packet](http://npm.im/mqtt-packet).

In the new MQTT.js this logic is handled by 
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L188-L203
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L230-L234
https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L695

This exact problem happened both in low-powered clients and high-traffic broker. Especially on reconnects with offline mode. I am still working to solve the latter on Mosca.

**Comment by rmg** [comment]
Unless the `getDelay()` is written _very_ carefully, or `trySend()` has some undescribed nuances, the delay approach would simple delay the flood, not actually slow it.

**Comment by rmg** [comment]
@mcollina it sounds like the biggest problem is the fundamental conflict between push/events and pull/streams.

It would probably be too big of a change, but it would be possible to address this by exposing an object-mode `stream.Readable` instead of an `EventEmitter`. And that would only even be possible for message _queues_, not other patterns like buses, etc.

**Comment by mcollina** [comment]
The underlining problem is that `EventEmitter` does not respect backpressure. My variant does: https://github.com/mcollina/mqemitter.

**Comment by ritch** [comment]
> it would be possible to address this by exposing an object-mode stream.Readable instead of an EventEmitter. And that would only even be possible for message queues, not other patterns like buses, etc.

Sounds good to me. This was actually in the original RFC. Can we keep the existing `on()` and `publish()` APIs? We'll atleast need a callback for `on()` (perhaps we can use `mqemitter`).

@rmg can you elaborate on:

> And that would only even be possible for message queues, not other patterns like buses, etc.

**Comment by mcollina** [comment]
I can also articulate the `mqemitter` idea into an almost standard EventEmitter interface, if this is something anybody would need/use. MQEmitter comes also with redis ([mqemitter-redis](http://npm.im/mqemitter-redis)) and mongo ([mqemitter-mongodb](http://npm.im/mqemitter-mongodb)) support.

**Comment by rmg** [comment]
@ritch bus and fanout topologies are in the same category as EventEmitters: broadcast with no guarantee of delivery. The idea of back pressure doesn't really make any more sense in those cases.

@mcollina mqemitter could use a check on the length of the handler and make the callback optional for the handlers. That would simplify cases where you want to do things like mix simple/sync and complex/async message handlers for topics. Would also be more compatible with the standard EventEmitter API.

**Comment by mcollina** [comment]
@rmg yes, it's a simple fix. Let me know if you want me to do it (in a while, traveling at the moment), or feel free to submit a pr.
